FROM python:3.9.5-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /tests/functional

COPY wait_for_it.sh .
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . /tests/functional
WORKDIR /tests/functional

CMD python utils/connections.py && pytest .
